### ISSUE TITLE
Improper composer repositories configuration

### ISSUE THREAD

**Issue by peter279k** [CovidResearch/ems.covidreporter.news#2]
As title, when using the `composer install -n` to install cached dependencies on this repository, I get following exception message:

```
Source path "/code/JWTGuardian" is not found for package phpexperts/jwt-guardian
```

It seems that the configuration is not proper and the improper configuration is as follows on `composer.json`:

```
......
"repositories": [
        {
            "type": "path",
            "url": "/code/JWTGuardian"
        }
    ]
......
```

I think it should use `vcs` type to set repository rather than using the local file path.

**Comment by hopeseekr** [comment]
It can't be helped. JWTGuardian isn't published, at least not fully.

THis ems.covidreporter.news project isn't designed for 3rd-party use, so this is a definite WONT_FIX at this time.

I have over 50% modified JWTGuardian but it's not field tested, so i can't pub it yet.
